.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. daylight_qt test_daylight_qt
clean: FORCE
	$(MAKE) -C .. daylight_qt_clean test_daylight_qt_clean
check: FORCE
	$(MAKE) -C .. test_daylight_qt_check
daylight-qt daylight-qt.exe: FORCE
	 $(MAKE) -C .. daylight_qt
